import Foundation

extension ShoppingItemSuggestion {
    static let catalog: [ShoppingItemSuggestion] = [
        ShoppingItemSuggestion(name: "Milk", symbolName: "drop", category: .dairy),
        ShoppingItemSuggestion(name: "Eggs", symbolName: "circle.grid.2x2", category: .dairy),
        ShoppingItemSuggestion(name: "Butter", symbolName: "cube", category: .dairy),
        ShoppingItemSuggestion(name: "Cheese", symbolName: "cube.fill", category: .dairy),
        ShoppingItemSuggestion(name: "Yogurt", symbolName: "cup.and.saucer", category: .dairy),
        ShoppingItemSuggestion(name: "Cream", symbolName: "drop.fill", category: .dairy),
        ShoppingItemSuggestion(name: "Sour Cream", symbolName: "cup.and.saucer.fill", category: .dairy),
        ShoppingItemSuggestion(name: "Cottage Cheese", symbolName: "cube", category: .dairy),
        ShoppingItemSuggestion(name: "Bread", symbolName: "takeoutbag.and.cup.and.straw", category: .bakery),
        ShoppingItemSuggestion(name: "Bagels", symbolName: "circle", category: .bakery),
        ShoppingItemSuggestion(name: "Tortillas", symbolName: "circle.dashed", category: .bakery),
        ShoppingItemSuggestion(name: "Apples", symbolName: "apple.logo", category: .produce),
        ShoppingItemSuggestion(name: "Bananas", symbolName: "leaf", category: .produce),
        ShoppingItemSuggestion(name: "Oranges", symbolName: "circle.fill", category: .produce),
        ShoppingItemSuggestion(name: "Berries", symbolName: "circle.grid.cross", category: .produce),
        ShoppingItemSuggestion(name: "Grapes", symbolName: "circle.grid.3x3", category: .produce),
        ShoppingItemSuggestion(name: "Lemons", symbolName: "circle", category: .produce),
        ShoppingItemSuggestion(name: "Potatoes", symbolName: "circle.hexagongrid", category: .produce),
        ShoppingItemSuggestion(name: "Onions", symbolName: "circle.dotted", category: .produce),
        ShoppingItemSuggestion(name: "Tomatoes", symbolName: "circle.fill", category: .produce),
        ShoppingItemSuggestion(name: "Lettuce", symbolName: "leaf", category: .produce),
        ShoppingItemSuggestion(name: "Spinach", symbolName: "leaf.fill", category: .produce),
        ShoppingItemSuggestion(name: "Carrots", symbolName: "carrot", category: .produce),
        ShoppingItemSuggestion(name: "Broccoli", symbolName: "leaf.circle", category: .produce),
        ShoppingItemSuggestion(name: "Cucumber", symbolName: "capsule", category: .produce),
        ShoppingItemSuggestion(name: "Chicken", symbolName: "fork.knife", category: .meatAndSeafood),
        ShoppingItemSuggestion(name: "Ground Beef", symbolName: "fork.knife.circle", category: .meatAndSeafood),
        ShoppingItemSuggestion(name: "Bacon", symbolName: "flame", category: .meatAndSeafood),
        ShoppingItemSuggestion(name: "Salmon", symbolName: "fish", category: .meatAndSeafood),
        ShoppingItemSuggestion(name: "Tuna", symbolName: "fish.circle", category: .meatAndSeafood),
        ShoppingItemSuggestion(name: "Rice", symbolName: "shippingbox", category: .pantry),
        ShoppingItemSuggestion(name: "Pasta", symbolName: "takeoutbag.and.cup.and.straw", category: .pantry),
        ShoppingItemSuggestion(name: "Noodles", symbolName: "takeoutbag.and.cup.and.straw.fill", category: .pantry),
        ShoppingItemSuggestion(name: "Flour", symbolName: "shippingbox.fill", category: .pantry),
        ShoppingItemSuggestion(name: "Sugar", symbolName: "cube", category: .pantry),
        ShoppingItemSuggestion(name: "Brown Sugar", symbolName: "cube.fill", category: .pantry),
        ShoppingItemSuggestion(name: "Coffee", symbolName: "cup.and.saucer", category: .pantry),
        ShoppingItemSuggestion(name: "Tea", symbolName: "mug", category: .pantry),
        ShoppingItemSuggestion(name: "Cereal", symbolName: "rectangle.grid.2x2", category: .pantry),
        ShoppingItemSuggestion(name: "Oats", symbolName: "leaf", category: .pantry),
        ShoppingItemSuggestion(name: "Peanut Butter", symbolName: "circle.hexagongrid.fill", category: .pantry),
        ShoppingItemSuggestion(name: "Jam", symbolName: "cylinder", category: .pantry),
        ShoppingItemSuggestion(name: "Honey", symbolName: "drop", category: .pantry),
        ShoppingItemSuggestion(name: "Olive Oil", symbolName: "drop.fill", category: .pantry),
        ShoppingItemSuggestion(name: "Vinegar", symbolName: "drop", category: .pantry),
        ShoppingItemSuggestion(name: "Salt", symbolName: "sparkles", category: .pantry),
        ShoppingItemSuggestion(name: "Pepper", symbolName: "sparkle", category: .pantry),
        ShoppingItemSuggestion(name: "Canned Beans", symbolName: "cylinder", category: .pantry),
        ShoppingItemSuggestion(name: "Canned Tomatoes", symbolName: "cylinder.fill", category: .pantry),
        ShoppingItemSuggestion(name: "Soup", symbolName: "takeoutbag.and.cup.and.straw", category: .pantry),
        ShoppingItemSuggestion(name: "Crackers", symbolName: "square.grid.3x3", category: .pantry),
        ShoppingItemSuggestion(name: "Chips", symbolName: "bag", category: .pantry),
        ShoppingItemSuggestion(name: "Chocolate", symbolName: "birthday.cake", category: .pantry),
        ShoppingItemSuggestion(name: "Ice Cream", symbolName: "snowflake", category: .frozen),
        ShoppingItemSuggestion(name: "Frozen Vegetables", symbolName: "snowflake.circle", category: .frozen),
        ShoppingItemSuggestion(name: "Toilet Paper", symbolName: "toilet", category: .household),
        ShoppingItemSuggestion(name: "Paper Towels", symbolName: "scroll", category: .household),
        ShoppingItemSuggestion(name: "Tissues", symbolName: "shippingbox", category: .household),
        ShoppingItemSuggestion(name: "Trash Bags", symbolName: "trash", category: .household),
        ShoppingItemSuggestion(name: "Batteries", symbolName: "battery.100percent", category: .household),
        ShoppingItemSuggestion(name: "Light Bulbs", symbolName: "lightbulb", category: .household),
        ShoppingItemSuggestion(name: "Foil", symbolName: "rectangle.stack", category: .household),
        ShoppingItemSuggestion(name: "Plastic Wrap", symbolName: "rectangle.on.rectangle", category: .household),
        ShoppingItemSuggestion(name: "Parchment Paper", symbolName: "doc.text", category: .household),
        ShoppingItemSuggestion(name: "Dish Soap", symbolName: "bubbles.and.sparkles", category: .cleaning),
        ShoppingItemSuggestion(name: "Laundry Detergent", symbolName: "washer", category: .cleaning),
        ShoppingItemSuggestion(name: "Cleaning Spray", symbolName: "sparkles", category: .cleaning),
        ShoppingItemSuggestion(name: "Sponges", symbolName: "sparkles.rectangle.stack", category: .cleaning),
        ShoppingItemSuggestion(name: "Shampoo", symbolName: "shower", category: .personalCare),
        ShoppingItemSuggestion(name: "Conditioner", symbolName: "shower.fill", category: .personalCare),
        ShoppingItemSuggestion(name: "Toothpaste", symbolName: "mouth", category: .personalCare),
        ShoppingItemSuggestion(name: "Hand Soap", symbolName: "hands.sparkles", category: .personalCare),
        ShoppingItemSuggestion(name: "Wet Wipes", symbolName: "hands.sparkles", category: .personalCare),
        ShoppingItemSuggestion(
            name: "Razor Blades",
            symbolName: "scissors",
            category: .personalCare,
            searchKeywords: ["Shave", "Shaving", "Shaver"]
        ),
        ShoppingItemSuggestion(
            name: "Shaving Cream",
            symbolName: "bubbles.and.sparkles",
            category: .personalCare,
            searchKeywords: ["Shave"]
        ),
        ShoppingItemSuggestion(
            name: "Shaving Foam",
            symbolName: "bubbles.and.sparkles",
            category: .personalCare,
            searchKeywords: ["Shave"]
        ),
        ShoppingItemSuggestion(name: "Cat Litter", symbolName: "cat", category: .pets),
        ShoppingItemSuggestion(name: "Cat Food", symbolName: "cat", category: .pets),
        ShoppingItemSuggestion(name: "Dog Food", symbolName: "dog", category: .pets),
        ShoppingItemSuggestion(name: "Pet Treats", symbolName: "pawprint", category: .pets),
        ShoppingItemSuggestion(name: "Pet Shampoo", symbolName: "shower", category: .pets),
        ShoppingItemSuggestion(name: "Pet Waste Bags", symbolName: "bag", category: .pets),
        ShoppingItemSuggestion(name: "Fish Food", symbolName: "fish", category: .pets),
        ShoppingItemSuggestion(name: "Bird Seed", symbolName: "bird", category: .pets),
        ShoppingItemSuggestion(name: "Rabbit Food", symbolName: "hare", category: .pets),
        ShoppingItemSuggestion(name: "Turtle Food", symbolName: "tortoise", category: .pets),
        ShoppingItemSuggestion(name: "Pet Brush", symbolName: "scissors", category: .pets),
        ShoppingItemSuggestion(name: "Flea Treatment", symbolName: "cross.case", category: .pets),
        ShoppingItemSuggestion(name: "Pet Medicine", symbolName: "pills", category: .pets),
        ShoppingItemSuggestion(name: "Pet Bedding", symbolName: "house", category: .pets)
    ]
}
